services:
  app:
    image: golang:1.24.0-bullseye
    container_name: go-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    command: >
      bash -c '
      go install github.com/air-verse/air@latest
      && air --build.cmd "go build -o tmp/api main.go" --build.bin "./tmp/api"
      '

  db:
    image: postgres:17.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: